# fly.toml app configuration file generated for matsumo-me-kmp on 2025-02-17T19:31:34+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matsumo-me-kmp"
primary_region = "nrt"

[build]

[env]
PORT = "9090"

[http_service]
internal_port = 9090
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
