[versions]
# Application
versionName = "2.0.2"
versionCode = "16"

# Gradle
gradle = "8.2.0"

# Kotlin
kotlin = "1.9.22"
kotlinWrapper = "1.0.0-pre.709"

# KotlinX
kotlinxCoroutines = "1.7.3"
kotlinxDatetime = "0.5.0"
kotlinxSerializationJson = "1.6.2"
kotlinxImmutable = "0.3.7"

# KMP
kmpCompose = "1.6.0"
kmpComplete = "1.1.0"

# Google
ksp = "1.9.22-1.0.17"

# Navigation
decompose = "3.0.0-alpha08"
essenty = "2.0.0-alpha07"

# Others
koin = "3.6.0-alpha3"
ktor = "3.0.0-wasm2"
coil = "2.5.0"
coil3 = "3.0.0-alpha06"
jsoup = "1.16.1"
ksoup = "0.1.2"
uuid = "0.8.2"
haze = "0.6.0"
composeWebView = "1.8.8"
windowSize = "0.5.0"
detekt = "1.23.4"
libraries = "10.9.1"
buildKonfig = "0.15.1"
twitterComposeRule = "0.0.26"

# Debugs
firebase = "32.7.2"
napier = "2.7.1"

[plugins]
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"  }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "libraries" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kmpCompose = { id = "org.jetbrains.compose", version.ref = "kmpCompose" }
kmpComplete = { id = "com.louiscad.complete-kotlin", version.ref = "kmpComplete" }
kmpKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }

[libraries]
## Dependency of to include build-logic
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
build-konfig-gradlePlugin = { group = "com.codingfeline.buildkonfig", name = "buildkonfig-gradle-plugin", version.ref = "buildKonfig" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

# Kotlin
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# Kotlin Wrapper
kotlin-wrapper-bom = { module = "org.jetbrains.kotlin-wrappers:kotlin-wrappers-bom", version.ref = "kotlinWrapper" }
kotlin-wrapper-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser" }
kotlin-wrapper-react = { module = "org.jetbrains.kotlin-wrappers:kotlin-react" }
kotlin-wrapper-react-dom = { module = "org.jetbrains.kotlin-wrappers:kotlin-react-dom" }

# KotlinX
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core-wasm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-wasm-js", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }

# Navigation
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
essenty-parcelable = { module = "com.arkivanov.essenty:parcelable", version.ref = "essenty" }
essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenty" }

# Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core"  }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-annotation = { module = "io.insert-koin:koin-annotation" }

# Ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktot-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Others
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-network = { module = "io.coil-kt.coil3:coil-network", version.ref = "coil3" }
coil3-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil3" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
window-size = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "windowSize" }
placeholder = { module = "com.eygraber:compose-placeholder-material3", version = "1.0.7" }
libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "libraries" }
libraries-ui = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "libraries" }
twitter-compose-rule = { module = "com.twitter.compose.rules:detekt", version.ref = "twitterComposeRule" }

# Debugs
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

[bundles]
infra = [
    "kotlin-stdlib",
    "kotlin-reflect",
    "kotlinx-datetime",
    "kotlinx-serialization-json",
    "kotlinx-collections-immutable",
    "kotlinx-coroutines-core",
    "napier",
]

ui-common = [
    "coil3-compose",
    "window-size",
]

ktor = [
    "ktor-core",
    "ktor-content-negotiation",
    "ktor-serialization-json",
    "ktot-logging",
]

koin = [
    "koin-core",
    "koin-compose",
]

decompose = [
    "decompose",
    "decompose-compose",
    "essenty-lifecycle",
]
