name: Backend Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: "matsumotodaichi0922@gmail.com"
